src/Entity/Abonnement.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AbonnementRepository")
 */
class Abonnement
{
    const TYPEABONNEMENT = array(
       1 => array(
                1 => 'Mensuel',
                2 => 5000
        ),
        2 => array(
            1 => 'Trimestruel',
            2 => 15000
        ),
        3 => array(
            1 => 'Semestruel',
            2 => 25000
        ),
        4 => array(
            1 => 'Annuel',
            2 => 40000
        )

    );
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $finish_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $typeAbonnement;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $montant;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Vehicule", inversedBy="abonnements")
     */
    private $id_vehicule;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getFinishAt(): ?\DateTimeInterface
    {
        return $this->finish_at;
    }

    public function setFinishAt(\DateTimeInterface $finish_at): self
    {
        $this->finish_at = $finish_at;

        return $this;
    }

    public function getTypeAbonnement(): ?string
    {
        return $this->typeAbonnement;
    }

    public function setTypeAbonnement(string $typeAbonnement): self
    {
        $this->typeAbonnement = $typeAbonnement;

        return $this;
    }

    public function getMontant()
    {
        return $this->montant;
    }

    public function setMontant($montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getIdVehicule(): ?Vehicule
    {
        return $this->id_vehicule;
    }

    public function setIdVehicule(?Vehicule $id_vehicule): self
    {
        $this->id_vehicule = $id_vehicule;

        return $this;
    }
}

templates/pages/faq.html.twig
{% extends 'base.html.twig' %}

{% block title 'FAQ' %}
{% block slider '' %}
{% block body %}
    {% include'default/head2.html.twig' %}
    <div class="row">
        <div class="col-md-12">
            <img src="/build/img/14.jpg" width="100%" height="400px" alt="">
        </div>
    </div>
    <div class="container mt-5">
        <div class="row">
            <div class="offset-md-3 col-md-6">
                <h1 class="deepshd text-center"> Fret-Online.sn </h1>
            </div>
        </div>
        <section class="features-icons bg-light text-center mt-3">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                            <div class="features-icons-icon d-flex">
                                <i class="fa fa-desktop m-auto text-primary"></i>
                            </div>
                            <h3>Fully Responsive</h3>
                            <p class="lead mb-0">This theme will look great on any device, no matter the size!</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                            <div class="features-icons-icon d-flex">
                                <i class="fa fa-android m-auto text-primary"></i>
                            </div>
                            <h3>Fret 4 Ready</h3>
                            <p class="lead mb-0">Featuring the latest build of the new framework!</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="features-icons-item mx-auto mb-0 mb-lg-3">
                            <div class="features-icons-icon d-flex">
                                <i class="fa fa-check m-auto text-primary"></i>
                            </div>
                            <h3>Easy to Use</h3>
                            <p class="lead mb-0">Ready to use with your own content, or customize the source files!</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>
{% endblock %}

templates/pages/fret-en-direct.html.twig
{% extends 'base.html.twig' %}

{% block title 'creation abonné' %}
{% block slider '' %}
{% block body %}
    <div class="jumbotron">
        <div class="col-md-2 mt-4">
            <h3>Frêt en direct</h3>
            <div class="progress mb-4">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 100%" aria-valuenow="50"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
        <div class="container">
            <div class="card offset-md-1 col-md-10 mt-3" style="margin-bottom: 40px;">
                {{ form_start(form) }}
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="">Localité</label>
                        <div>{{ form_widget(form.localite) }}</div>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="">Type Vehicule</label>
                        <div>{{ form_errors(form.typeVehicule) }}</div>
                        <div>{{ form_widget(form.typeVehicule) }}</div>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="">Quantité minimum</label>
                        <div>{{ form_errors(form.tonnage) }}</div>
                        <div>{{ form_widget(form.tonnage) }}</div>
                    </div>
                    <div class="form-group col-md-3 text-center">
                        <button type="submit" class="btn btn-primary mt-4">Search</button>
                    </div>
                </div>
                {{ form_end(form) }}
            </div>

            <div class="card offset-1 col-md-10">
                <table class="table table-striped">
                    {% for voyage in voyages %}
                        <tr>
                            <td>{{ voyage.idVehicule.matricule}}</td>
                            <td>{{ voyage.}}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Home' %}

{% block body %}
    {% include'default/head1.html.twig' %}
    <div class="container mt-4">
        <div class="row">
            <div class="offset-md-1 col-md-6">
                <div class="progress mb-4">
                    <div class="progress-bar bg-primary" role="progressbar" style="width: 100%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <h3 class="text-center">Fret-Online.sn c'est :</h3>
                <div>
                    <p ><i class="fa fa-handshake-o text-md-left text-primary"></i>&nbsp;&nbsp; Une mise en relation directe et sans intermédiaire entre differents operateurs du transport.</p>
                    <p ><i class="fa fa-clock-o text-md-left text-primary"></i>&nbsp;&nbsp;Une actualisation en temps réel des trajets de véhicules</p>
                    <p ><i class="fa fa-briefcase text-md-left text-primary"></i>&nbsp;&nbsp;Un espace de présentation pour votre entreprise</p>
                    <p ><i class="fa fa-bell text-md-left text-primary"></i>&nbsp;&nbsp;Des alertes en « temps réel » sur les offres de fret et sur les recherches de véhicules</p>
                    <p ><i class="fa fa-phone-square text-md-left text-primary"></i>&nbsp;&nbsp;Plus de contacts et de visibilité avec les annuaires « fret-online.sn »</p>
                    <p ><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="progress mb-4">
                    <div class="progress-bar bg-primary" role="progressbar" style="width: 100%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <img src="/build/img/12.png" alt="" style="width: 100%; height: 350px;border-radius: 20px">
            </div>
        </div>
        <div class="row" style="margin-top: 80px;">
            <div class="col-md-4">
                <h3>Comment ça fonctionne ?</h3>
                <div class="progress mb-4">
                    <div class="progress-bar bg-primary" role="progressbar" style="width: 100%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
        </div>
    <div class="container mt-4">
        <div class="card-deck mb-3 text-center">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Affréteur/Courtier</h4>
                </div>
                <div class="card-body">
                    <h3 class="card-title pricing-card-title">0 Fcfa<small class="text-muted"></small></h3>
                    <ul class="list-unstyled mt-3 mb-4 text-left">
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;Notification en temps réel.</li>
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;Possibilité de poster des offres.</li>
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;Recherche élargie pour + de résultats.</li>
                        <li><i class="fa fa-close" style="color:#a71d2a;"></i>&nbsp;Espace de présentation entreprise.</li>
                        <li><i class="fa fa-close" style="color:#a71d2a;"></i>&nbsp;3 camions gratuits.</li>
                        <li><i class="fa fa-close" style="color:#a71d2a;"></i>&nbsp;Incription illimitté camions</li>
                        <li><i class="fa fa-close" style="color:#a71d2a;"></i>&nbsp;MAJ trajet vehicule en temps réel.</li>
                        <li><i class="fa fa-close" style="color:#a71d2a;"></i>&nbsp;Acces aux annuairex entreprises</li>
                        <li><i class="fa fa-close" style="color:#a71d2a;"></i>&nbsp;Choix type abonnement</li>
                    </ul>
                    <a href="{{ path('create_compte') }}" class="text-decoration-none">
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</button> </a>
                </div>
            </div>
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Transporteurs</h4>
                </div>
                <div class="card-body">
                    <h3 class="card-title pricing-card-title">0 Fcfa <small class="text-muted"></small></h3>
                    <ul class="list-unstyled mt-3 mb-4 text-left">
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;Notification en temps réel.</li>
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;Possibilité de poster des offres.</li>
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;Recherche élargie pour + de résultats.</li>
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;Espace de présentation entreprise.</li>
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;3 camions gratuits.</li>
                        <li><i class="fa fa-close" style="color:#a71d2a;"></i>&nbsp;Incription illimitté camions</li>
                        <li><i class="fa fa-close" style="color:#a71d2a;"></i>&nbsp;MAJ trajet vehicule en temps réel.</li>
                        <li><i class="fa fa-close" style="color:#a71d2a;"></i>&nbsp;Acces aux annuairex entreprises</li>
                        <li><i class="fa fa-close" style="color:#a71d2a;"></i>&nbsp;Choix type abonnement</li>
                    </ul>
                    <a href="{{ path('create_compte') }}" class="text-decoration-none">
                    <button type="button" class="btn btn-lg btn-block btn-primary">Get started</button></a>
                </div>
            </div>
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Transporteur/Pro</h4>
                </div>
                <div class="card-body">
                    <h3 class="card-title pricing-card-title">XXXX Fcfa <small class="text-muted">/Camion</small></h3>
                    <ul class="list-unstyled mt-3 mb-4 text-left">
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;Notification en temps réel.</li>
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;Possibilité de poster des offres.</li>
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;Recherche élargie pour + de résultats.</li>
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;Espace de présentation entreprise.</li>
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;3 camions gratuits.</li>
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;Incription illimitté camions</li>
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;MAJ trajet vehicule en temps réel.</li>
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;Acces aux annuairex entreprises</li>
                        <li><i class="fa fa-check-circle" style="color:#2C3E50;"></i>&nbsp;Choix type abonnement</li>
                    </ul>
                    <a href="{{ path('create_compte') }}" class="text-decoration-none">
                    <button type="button" class="btn btn-lg btn-block btn-primary" >Contact us</button></a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/login.html.twig
{% extends 'base.html.twig' %}
{% block title 'Login' %}
{% block slider '' %}
    {% block body %}
        <div class="container mt-4 ">
            <div class="card col-md-10">
                <div class="card-header"></div>
                <div class="card-body">
                    {{ form_start(login) }}
                    {{ form_widget(login)}}
                    <button type="submit" class="btn btn-primary btn-labeled pull-right">Sign in<span class="btn-label btn-label-right"><i class="fa fa-check"></i></span></button>
                    {{ form_end(login) }}
                </div>
            </div>
        </div>
    {% endblock %}