src/Entity/Abonnes.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Asset;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
 * Abonnes
 *
 * @ORM\Table(name="abonnes")
 * @ORM\Entity(repositoryClass="App\Repository\AbonnesRepository")
 * @Vich\Uploadable()
 * @UniqueEntity("ninea")
 * @UniqueEntity("email")
 * @UniqueEntity("telephone")
 */
class Abonnes implements UserInterface, \Serializable
{
    const TYPEAB = array(
        1=>'Affreteur/Courtier',
        2=>'Transporteur'
    );
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @Asset\Regex("/^[' a-zA-Z]+$/")
     * @var string
     * @ORM\Column(name="nom", type="string", length=70, nullable=false)
     */
    private $nom;

    /**
     * @Asset\Regex("/^[0-9]{9}$/")
     * @var string
     *
     * @ORM\Column(name="ninea", type="string", length=100, nullable=false)
     */
    private $ninea;

    /**
     * @Asset\Regex("/^[0-9]{9}$/")
     * @var string
     * @Asset\Length(min=5,max=10)
     * @ORM\Column(name="telephone", type="string", length=25, nullable=true)
     */
    private $telephone;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=100, nullable=false)
     */
    private $email;
    /**
     * @var File|null
     * @Vich\UploadableField( mapping="abonnes_profil",fileNameProperty="file")
     */
    private $imageProfil;
    /**
     * @var string|null
     *
     * @ORM\Column(name="file", type="string", length=100, nullable=true)
     */
    private $file;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=200, nullable=false)
     */
    private $password;

    /**
     * @var int
     * @ORM\Column(type="integer")
     */
    private $typeAbonne;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Entreprise", inversedBy="abonnes")
     */
    private $id_entreprise;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Messages", mappedBy="id_Abonne")
     */
    private $ListeMessage;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Vehicule", mappedBy="idAbonne")
     */
    private $listeVehicule;

    public function __construct()
    {
        $this->ListeMessage = new ArrayCollection();
        $this->listeVehicule = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNinea(): ?string
    {
        return $this->ninea;
    }

    public function setNinea(?string $ninea): self
    {
        $this->ninea = $ninea;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(?string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getTypeAbonneValue():string
    {
        return self::TYPEAB[$this->getTypeAbonne()];
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return array (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return ['ROLE_USER'];
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        // TODO: Implement getUsername() method.
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {

    }

    /**
     * String representation of object
     * @link http://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()
    {
        return serialize(
            [
                $this->id,
                $this->email,
                $this->password
            ]
        );
    }

    /**
     * Constructs the object
     * @link http://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->email,
            $this->password
            ) = unserialize($serialized, ['allowed_classes' => false]);
    }

    public function getTypeAbonne(): ?int
    {
        return $this->typeAbonne;
    }

    public function setTypeAbonne(int $typeAbonne): self
    {
        $this->typeAbonne = $typeAbonne;

        return $this;
    }

    /**
     * @return null|File
     */
    public function getImageProfil(): ?File
    {
        return $this->imageProfil;
    }

    /**
     * @param null|File $imageProfil
     */
    public function setImageProfil(?File $imageProfil): void
    {
        $this->imageProfil = $imageProfil;
        if ($this->imageProfil instanceof UploadedFile)
        {
            $this->created_at = new \DateTime('now');
        }
        $this->created_at = new \DateTime('now');
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getIdEntreprise(): ?Entreprise
    {
        return $this->id_entreprise;
    }

    public function setIdEntreprise(?Entreprise $id_entreprise): self
    {
        $this->id_entreprise = $id_entreprise;

        return $this;
    }

    /**
     * @return Collection|Messages[]
     */
    public function getListeMessage(): Collection
    {
        return $this->ListeMessage;
    }

    public function addListeMessage(Messages $listeMessage): self
    {
        if (!$this->ListeMessage->contains($listeMessage)) {
            $this->ListeMessage[] = $listeMessage;
            $listeMessage->setIdAbonne($this);
        }

        return $this;
    }

    public function removeListeMessage(Messages $listeMessage): self
    {
        if ($this->ListeMessage->contains($listeMessage)) {
            $this->ListeMessage->removeElement($listeMessage);
            // set the owning side to null (unless already changed)
            if ($listeMessage->getIdAbonne() === $this) {
                $listeMessage->setIdAbonne(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Vehicule[]
     */
    public function getListeVehicule(): Collection
    {
        return $this->listeVehicule;
    }

    public function addListeVehicule(Vehicule $listeVehicule): self
    {
        if (!$this->listeVehicule->contains($listeVehicule)) {
            $this->listeVehicule[] = $listeVehicule;
            $listeVehicule->setIdAbonne($this);
        }

        return $this;
    }

    public function removeListeVehicule(Vehicule $listeVehicule): self
    {
        if ($this->listeVehicule->contains($listeVehicule)) {
            $this->listeVehicule->removeElement($listeVehicule);
            // set the owning side to null (unless already changed)
            if ($listeVehicule->getIdAbonne() === $this) {
                $listeVehicule->setIdAbonne(null);
            }
        }

        return $this;
    }

}

src/Entity/Entreprise.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;



/**
 * @ORM\Entity(repositoryClass="App\Repository\EntrepriseRepository")
 * @Vich\Uploadable()
 * @UniqueEntity("Tel")
 */
class Entreprise
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Regex("/^[A-Za-z0-9 '-]*$/")
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @Assert\Regex("/^[0-9]{9}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $ninea;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img;
    /**
     * @var File|null
     * @Vich\UploadableField( mapping="entreprise_logo",fileNameProperty="img")
     */
    private $imageLogo;
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbreAbonnes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Abonnes", mappedBy="id_entreprise")
     */
    private $abonnes;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Ville;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\ZoneIntervention", mappedBy="idEntreprise")
     */
    private $ListeZone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $compagnieAssurance;

    public function __construct()
    {
        $this->abonnes = new ArrayCollection();
        $this->ListeZone = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNinea(): ?string
    {
        return $this->ninea;
    }

    public function setNinea(string $ninea): self
    {
        $this->ninea = $ninea;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getNbreAbonne(): ?int
    {
        return $this->nbreAbonnes;
    }

    public function setNbreAbonne(?int $nbreAbonne): self
    {
        $this->nbreAbonnes = $nbreAbonne;

        return $this;
    }

    /**
     * @return Collection|Abonnes[]
     */
    public function getAbonnes(): Collection
    {
        return $this->abonnes;
    }

    public function addAbonne(Abonnes $abonne): self
    {
        if (!$this->abonnes->contains($abonne)) {
            $this->abonnes[] = $abonne;
            $abonne->setIdEntreprise($this);
        }

        return $this;
    }

    public function removeAbonne(Abonnes $abonne): self
    {
        if ($this->abonnes->contains($abonne)) {
            $this->abonnes->removeElement($abonne);
            // set the owning side to null (unless already changed)
            if ($abonne->getIdEntreprise() === $this) {
                $abonne->setIdEntreprise(null);
            }
        }

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(?string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(?string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageLogo(): ?File
    {
        return $this->imageLogo;
    }

    /**
     * @param File|null $imageLogo
     */
    public function setImageLogo(?File $imageLogo): void
    {
        $this->imageLogo = $imageLogo;
        if ($this->imageLogo instanceof UploadedFile)
        {
            $this->create_at = new \DateTime('now');
        }
        $this->create_at = new \DateTime('now');
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    /**
     * @return Collection|ZoneIntervention[]
     */
    public function getListeZone(): Collection
    {
        return $this->ListeZone;
    }

    public function addListeZone(ZoneIntervention $listeZone): self
    {
        if (!$this->ListeZone->contains($listeZone)) {
            $this->ListeZone[] = $listeZone;
            $listeZone->addIdEntreprise($this);
        }

        return $this;
    }

    public function removeListeZone(ZoneIntervention $listeZone): self
    {
        if ($this->ListeZone->contains($listeZone)) {
            $this->ListeZone->removeElement($listeZone);
            $listeZone->removeIdEntreprise($this);
        }

        return $this;
    }

    public function getCompagnieAssurance(): ?string
    {
        return $this->compagnieAssurance;
    }

    public function setCompagnieAssurance(?string $compagnieAssurance): self
    {
        $this->compagnieAssurance = $compagnieAssurance;

        return $this;
    }

}

templates/abonne/create.html.twig
{% extends 'base.html.twig' %}

{% block title 'creation abonné' %}
{% block slider '' %}
{% block body %}
    <div class="jumbotron">
    <div class="col-md-3 mt-4">
        <h3>Création de compte</h3>
        <div class="progress mb-4">
            <div class="progress-bar bg-primary" role="progressbar" style="width: 100%" aria-valuenow="50"
                 aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
    <div class="container">
        <div class="card offset-md-1 col-md-10 mt-3" style="margin-bottom: 40px;">
            {{ form_start(form) }}
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="">Nom</label>
                    <div>{{ form_errors(form.nom) }}</div>
                    <div>{{ form_widget(form.nom) }}</div>
                </div>
                <div class="form-group col-md-6">
                    <label for="">Prenom</label>
                    <div>{{ form_errors(form.prenom) }}</div>
                    <div>{{ form_widget(form.prenom) }}</div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="">Ninea</label>
                    {% if sub_error['ninea'] != "" %}
                        <div class="small text-danger">
                            <span class="bg-danger text-white font-weight-bold" style=";border-radius: 5px;">
                            ERREUR</span> Ce ninea existe dejà.
                        </div>
                    {% endif %}
                    <div>{{ form_widget(form.ninea) }}</div>
                </div>
                <div class="form-group col-md-6">
                    <label for="typeAbonne">Type de Compte</label>
                    <div>{{ form_errors(form.typeAbonne) }}</div>
                    <div>{{ form_widget(form.typeAbonne) }}</div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="Email">Email</label>
                    {% if sub_error['email'] != "" %}
                        <div class="small text-danger">
                            <span class="bg-danger text-white font-weight-bold" style=";border-radius: 5px;">
                            ERREUR</span> Cet émail existe dejà.
                        </div>
                    {% endif %}
                    <div>{{ form_widget(form.email) }}</div>
                </div>
                <div class="form-group col-md-6">
                    <label for="tel">Téléphone</label>
                    {% if sub_error['tel'] != "" %}
                        <div class="small text-danger">
                            <span class="bg-danger text-white font-weight-bold" style=";border-radius: 5px;">
                            ERREUR</span> Ce format est incorrect ou existe dejà.
                        </div>
                    {% endif %}
                    <div>{{ form_widget(form.telephone) }}</div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="">Photo</label>
                    {% if sub_error['image'] != "" %}
                        <div class="small text-danger">
                            <span class="bg-danger text-white font-weight-bold" style=";border-radius: 5px;">
                            ERREUR</span> désole ce format n'est pas pris en charge.
                        </div>
                    {% endif %}
                    <div>{{ form_widget(form.imageProfil) }}</div>
                </div>
                <div class="form-group col-md-6">
                    <label for="Password">Mot de passe</label>
                    <div>{{ form_errors(form.password) }}</div>
                    <div>{{ form_widget(form.password) }}</div>
                </div>
            </div>
            <div class="form-group" style="margin-bottom: 100px;">
                {{ form_rest(form) }}
                <button type="submit" class="btn btn-primary btn-labeled pull-right">Valider&nbsp;<span
                            class="btn-label btn-label-right"><i class="fa fa-check"></i></span></button>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
</div>
{% endblock %}

templates/abonne/create_entreprise.html.twig
{% extends 'base.html.twig' %}

{% block title 'creation abonné' %}
{% block slider '' %}
{% block body %}
    <div class="jumbotron">
        <div class="col-md-3 mt-4">
            <h4>Ajouter votre Entreprise</h4>
            <div class="progress mb-4">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 100%" aria-valuenow="50"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                {% for message in app.flashes('success') %}
                    <div class="offset-md-3 col-md-6 text-center">
                        <p class="alert alert-success">{{ message }}</p>
                    </div>
                {% endfor %}
            </div>
            <div class="card offset-md-1 col-md-10 mt-3" style="margin-bottom: 40px;">
                {{ form_start(form) }}
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="">Nom</label>
                        <div>{{ form_errors(form.nom) }}</div>
                        <div>{{ form_widget(form.nom) }}</div>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="">Ninea</label>
                        <div>{{ form_errors(form.ninea) }}</div>
                        <div>{{ form_widget(form.ninea) }}</div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="">Ville</label>
                        <div>{{ form_errors(form.ville) }}</div>
                        <div>{{ form_widget(form.ville) }}</div>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="">Adresse</label>
                        <div>{{ form_errors(form.adresse) }}</div>
                        <div>{{ form_widget(form.adresse) }}</div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="">Telephone</label>
                        {% if sub_error['tel'] != "" %}
                            <div class="small text-danger">
                            <span class="bg-danger text-white font-weight-bold" style=";border-radius: 5px;">
                            ERREUR</span> Cet numero est incorrect ou existe dejà.
                            </div>
                        {% endif %}
                        <div>{{ form_widget(form.tel) }}</div>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="">Logo</label>
                        {% if sub_error['logo'] != "" %}
                            <div class="small text-danger">
                            <span class="bg-danger text-white font-weight-bold" style=";border-radius: 5px;">
                            ERREUR</span> Cet format n'est pris en charge
                            </div>
                        {% endif %}
                        <div>{{ form_widget(form.imageLogo) }}</div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="">Compagnie Assurance</label>
                        <div>{{ form_errors(form.compagnieAssurance) }}</div>
                        <div>{{ form_widget(form.compagnieAssurance) }}</div>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="">Zones Interventions</label>
                            <select name="zone[]" id="" aria-multiselectable="true" class="form-control" multiple="multiple">
                                {% for zone in zones %}
                                    <option value="{{ zone.id}}">{{ zone.nomZone }}</option>
                                {% endfor %}
                            </select>
                    </div>
                </div>
                <div class="row">
                    {{ form_rest(form) }}
                       <div class="offset-md-4 col-md-4">
                           <button type="submit" class="btn btn-primary btn-labeled pull-right">Valider&nbsp;<span
                                       class="btn-label btn-label-right"><i class="fa fa-check"></i></span></button>
                           <button type=""  class="btn btn-primary btn-labeled pull-left">
                               <a class="text-decoration-none" href="{{ path('user_espace') }}">Ignorer&nbsp;</a><span
                                       class="btn-label btn-label-right"><i class="fa fa-close"></i></span></button>
                       </div>
                </div>
                <p class="small text-danger mt-4"  style="margin-bottom: 50px;"><i class="fa fa-hand-o-right"></i>  Si vous travaillez pour votre propre compte vous pouvez ignorer.</p>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/abonne/edit.html.twig
{% extends 'base.html.twig' %}

{% block title 'creation abonné' %}
{% block slider '' %}
{% block body %}
    <div class="jumbotron">
        <div class="col-md-4 mt-4">
            <h3>Modification de compte</h3>
            <div class="progress mb-4">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 100%" aria-valuenow="50"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
        <div class="container">
            <div class="card offset-md-1 col-md-10 mt-3" style="margin-bottom: 40px;">
                {{ form_start(form) }}
                <div class="mt-3 " >{{ form_row(form.nom) }}</div>
                <div class=" ">{{ form_row(form.prenom) }}</div>
                <div class=" ">{{ form_row(form.ninea) }}</div>
                <div class=" ">{{ form_row(form.typeAbonne) }}</div>

                <div class=" ">{{ form_row(form.telephone) }}</div>
                <div class=" ">{{ form_row(form.email) }}</div>

                <div class=" ">
                    {{ form_row(form.imageProfil) }}
                </div>
                <div class=" ">{{ form_row(form.password) }}</div>
                <div class="" style="margin-bottom: 100px;">
                    {{ form_rest(form) }}
                    <button type="submit" class="btn btn-primary btn-labeled pull-right">Valider&nbsp;<span
                                class="btn-label btn-label-right"><i class="fa fa-check"></i></span></button>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}